// ERROR
export const ERROR = 'ERROR'

// SESSION
export const START_SESSION = 'START_SESSION'
export const SET_SESSION_USER = 'SET_SESSION_USER'
export const END_SESSION = 'END_SESSION'

// TRANSACTIONS
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const INSERT_TRANSACTION = 'INSERT_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'

// SYNC STATE
export const SET_SYNC_STATE = 'SET_SYNC_STATE'
