export const ERROR = 'ERROR'

export const SET_USER = 'SET_USER'
export const UN_USER = 'UNSET_USER'

export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const INSERT_TRANSACTION = 'INSERT_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'

export const SET_SYNC_STATE = 'SET_SYNC_STATE'
